### ISSUE TITLE
What is this NuGet package?

### ISSUE THREAD

**Issue by Thorium** [dopare/LinqKit.Core#1]
How is this different from https://github.com/scottksmith95/LINQKit ?

**Comment by dopare** [comment]
@Thorium this was a temporary workaround, I will close this project soon

**Comment by Thorium** [comment]
Ok. We were thinking that should we use non-EF-LinqKit as LinqKit.Core and then the LinqKit could have references to EF. As we used to have EF-references in LinqKit and now as they are gone, people are missing the features that there are no more. What do you think?

scottksmith95/LINQKit#49

**Comment by dopare** [comment]
@Thorium nice idea, I have added you to owners, so you could update as you wish

**Comment by Thorium** [comment]
Ok, thanks!

**Comment by StefH** [comment]
@dopare Can you please also add me as an owner ? (I'm also an owner for the LINQKit project on nuget)

**Comment by dopare** [comment]
@StefH sure, added.

**Comment by StefH** [comment]
Thanks.
